language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2

gemfile:
  - gemfiles/activerecord_3_1.gemfile
  - gemfiles/activerecord_3_2.gemfile
  - gemfiles/activerecord_4_0.gemfile
  - gemfiles/activerecord_4_1.gemfile
  - gemfiles/activerecord_4_2.gemfile

env:
  - DB=postgresql
  - DB=mysql
  - DB=sqlite3

sudo: false

before_script:
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'DROP DATABASE IF EXISTS sexy_scopes_spec;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'CREATE DATABASE sexy_scopes_spec;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS sexy_scopes_spec;'; fi"

script: bundle exec rake

matrix:
  allow_failures:
    - rvm: rbx-2

branches:
  only:
    - master
